package mainCodes;
use strict;
use warnings;

our %legalCodes = (
"xxx" => "ACU", #Air Conditioning Unit
"xxx" => "BAB", #Bridge Abutment - Top Face - 3D
"xxx" => "BAL", #Bridge Abut/Wingwall - Prismless - The outline of the face of the abutment
"xxx" =>           # and the face of the wingwalls.  A 2d line, usually collected prismless.
"xxx" => "BAR", #Stop Bar
"xxx" => "BAS", #Bridge Approach Slab
"xxx" => "BBA", #Bridge Deck Spot – Aggregate
"xxx" => "BBB", #Bridge Deck Spot – HMA
"xxx" => "BBC", #Bridge Deck Spot – Concrete
"xxx" => "BBG", #Buffalo Box - Gas
"xxx" => "BBR", #Bridge Deck Spot – Brick
"xxx" => "BBS", #Bridge Beam Seat Elevation - The bridge seat elevation.  For elevation only.
"xxx" =>           # Usually collected with the "hook".
"xxx" => "BBV", #Bridge Deck Spot – Vinyl
"xxx" => "BBW", #Buffalo Box - Water
"xxx" => "BCB", #Bridge Curb - Top Front
"xxx" => "BDB", #Bridge Deck Edge – Bit
"xxx" => "BDC", #Bridge Deck Edge – Conc
"xxx" => "BDT", #Bridge Deck Edge – Timber
"xxx" => "BEX", #Bridge Expansion Joint
"xxx" => "BHR", #Bridge Handrail
"xxx" => "BLC", #Bridge Low Element Elevation – Concrete - The bottom of the concrete bridge
"xxx" =>           # beams.  Usually taken at the beginning middle and end of each span of
"xxx" =>           # the bridge beams. Usually only required on the outside (upstream and 
"xxx" =>           # downstream) beams.
"xxx" => "BLS", #Bridge Low Element Elevation – Steel - The bottom of the steel bridge beams.
"xxx" =>           # Usually taken at the beginning middle and end oof each span of the
"xxx" =>           # bridge beams. Usually only required on the outside (upstream and
"xxx" =>           # downstream) beams.
"xxx" => "BLT", #Bridge Low Element Elevation – Timber - The bottom of the timber bridge
"xxx" =>           # beams.  Usually taken at the beginning middle and end of each span of
"xxx" =>           # the bridge beams. Usually only required on the outside (upstream and
"xxx" =>           # downstream) beams.
"xxx" => "BOL", #Post / Bollard
"xxx" => "BOR", #Soil Boring / Coring
"xxx" => "BPA", #Bridge Parapet – 3D
"xxx" => "BPC", #Bridge Pier - 2D Prismless - The outline of the face of the pier cap.
"xxx" =>           # A 2d line usually collected "prismless".
"xxx" => "BPR", #Bridge Pier - Top Face - 3D
"xxx" => "BPT", #Bridge Pier Top Elevation Only - The pier cap elevation - For elevation
"xxx" =>           # only.  Usually collected with the "hook".
"xxx" => "BRK", #Breakline
"xxx" => "BRR", #Barrier Wall - base
"xxx" => "BSC", #Bridge Scupper (drain)
"xxx" => "BSH", #Bush / Shrub
"xxx" => "BSL", #Bush Line / Hedgerow
"xxx" => "BSS", #Bridge Structural Steel Member (not low steel)
"xxx" => "BWL", #Bridge Backwall – 3D
"xxx" => "BWW", #Bridge Wingwall - Top Face & Back – 3D - The outline of the face and
"xxx" =>           # sides of the wingwall.  A 3d line with points at each elevation change.
"xxx" => "CBM", #Storm - CB - round open
"xxx" => "CKH", #Check horizontal control point
"xxx" => "CKV", #Check BM
"xxx" => "CLP", #Calculated Point
"xxx" => "CNA", #Pavement Crown – aggregate – use where no stripeing
"xxx" => "CNB", #Pavement Crown – HMA - use where no stripeing
"xxx" => "CNC", #Pavement Crown – Concrete - use where no stripeing
"xxx" => "CNP", #Canopy
"xxx" => "CNT", #Signal Cantilever/Mast Arm
"xxx" => "COL", #Column
"xxx" => "CPH", #Control Point
"xxx" => "CPT", #Cathodic Protection Test Station – Gas
"xxx" => "CRB", #Curb Top Back - concrete
"xxx" => "CRP", #Crop / Cultivation Line
"xxx" => "CRW", #Crosswalk
"xxx" => "CUB", #Storm-culvert-box
"xxx" => "CUE", #Storm-culvert-Elliptical
"xxx" => "CUP", #Storm-culvert-pipe
"xxx" => "DAM", #Dam/Levee Top
"xxx" => "DCA", #Driveway – Commercial – Aggregate
"xxx" => "DCB", #Driveway – Commercial – HMA
"xxx" => "DCC", #Driveway – Commercial – Concrete
"xxx" => "DCK", #Deck
"xxx" => "DCR", #Driveway – Commercial – Brick
"xxx" => "DFA", #Driveway – Field – Aggregate
"xxx" => "DFB", #Driveway – Field – HMA
"xxx" => "DFC", #Driveway – Field – Conc
"xxx" => "DFG", #Driveway – Field – Ground
"xxx" => "DFO", #Driveway – Field – Oil & Chip
"xxx" => "DFR", #Driveway – Field – Brick
"xxx" => "DPA", #Driveway – Public – Aggregate
"xxx" => "DPB", #Driveway – Public – HMA
"xxx" => "DPC", #Driveway – Public – Concrete
"xxx" => "DPR", #Driveway – Public – Brick
"xxx" => "DRA", #Driveway – Residential – Aggregate
"xxx" => "DRB", #Driveway – Residential – HMA
"xxx" => "DRC", #Driveway – Residential – Concrete
"xxx" => "DRR", #Driveway – Residential – Brick
"xxx" => "DSP", #Downspout
"xxx" => "DTH", #Ditch - Flowline
"xxx" => "DTP", #Paved Ditch Centerline
"xxx" => "EOA", #EOP Line – Aggregate
"xxx" => "EOB", #EOP Line – HMA
"xxx" => "EOC", #EOP Line – Concrete
"xxx" => "EOG", #EOP Line – Ground – Travelled Way
"xxx" => "EOO", #EOP Line – Oil & Chip
"xxx" => "EOR", #EOP Line – Brick
"xxx" => "FDA", #Found Survey Evidence - Traverse Point
"xxx" => "FDB", #Found Survey Evidence - Axle
"xxx" => "FDC", #Found Survey Evidence - Cut Cross
"xxx" => "FDD", #Found Survey Evidence - Concrete Monument
"xxx" => "FDE", #Found Survey Evidence - Crimp Pipe
"xxx" => "FDF", #Found Survey Evidence - Benchmark
"xxx" => "FDG", #Found Survey Evidence - GPS Monument
"xxx" => "FDH", #Found Survey Evidence - Control Point
"xxx" => "FDI", #Found Survey Evidence - Iron Pipe
"xxx" => "FDJ", #Found Survey Evidence - Nail
"xxx" => "FDK", #Found Survey Evidence - Nail & Washer/Shiner
"xxx" => "FDL", #Found Survey Evidence - PK Nail
"xxx" => "FDM", #Found Survey Evidence - Mag Nail
"xxx" => "FDN", #Found Survey Evidence - ROW Marker
"xxx" => "FDO", #Found Survey Evidence - RR Spike
"xxx" => "FDP", #Found Survey Evidence - Pole Barn Spike
"xxx" => "FDQ", #Found Survey Evidence - Stone
"xxx" => "FDR", #Found Survey Evidence - Cotton Picker Spindle
"xxx" => "FDS", #Found Survey Evidence - Hub
"xxx" => "FDT", #Found Survey Evidence - Cut Square
"xxx" => "FDU", #Found Survey Evidence - Rebar
"xxx" => "FDV", #Found Survey Evidence - Drill Hole
"xxx" => "FDW", #Found Survey Evidence - Brass Marker
"xxx" => "FDX", #Found Survey Evidence - Iron Rod/Pin
"xxx" => "FDY", #Found Survey Evidence - Notch
"xxx" => "FDZ", #Found Survey Evidence - Other
"xxx" => "FES", #Flared End Section
"xxx" => "FFL", #Finish Floor Elevation
"xxx" => "FNG", #Fence - Gate post
"xxx" => "FNI", #Fence – Iron
"xxx" => "FNL", #Fence – Chain Link
"xxx" => "FNM", #Fence – Masonry
"xxx" => "FNN", #Fence – Stone
"xxx" => "FNR", #Fence – Brick
"xxx" => "FNT", #Fence – Wood
"xxx" => "FNV", #Fence – Vinyl
"xxx" => "FNW", #Fence – Wire
"xxx" => "FNX", #Fence – Barbed Wire
"xxx" => "FOU", #Foundation
"xxx" => "GCC", #Building – Commercial – Concrete
"xxx" => "GCF", #Building – Commercial – Frame
"xxx" => "GCM", #Building – Commercial – Masonry
"xxx" => "GCN", #Building – Commercial – Stone
"xxx" => "GCR", #Building – Commercial – Brick
"xxx" => "GCS", #Building – Commercial – Steel
"xxx" => "GCT", #Building – Commercial – Timber/Log
"xxx" => "GND", #Ground Shot
"xxx" => "GPC", #Building – Residential – Concrete
"xxx" => "GPF", #Building – Public – Frame
"xxx" => "GPM", #Building – Public – Masonry
"xxx" => "GPN", #Building – Public – Stone
"xxx" => "GPR", #Building – Public – Brick
"xxx" => "GPS", #Building – Public – Steel
"xxx" => "GPT", #Building – Public – Timber/Log
"xxx" => "GRC", #Building – Residential – Concrete
"xxx" => "GRF", #Building – Residential – Frame
"xxx" => "GRL", #Guard Rail
"xxx" => "GRM", #Building – Residential – Masonry
"xxx" => "GRN", #Building – Residential – Stone
"xxx" => "GRR", #Building – Residential – Brick
"xxx" => "GRS", #Building – Residential – Steel
"xxx" => "GRT", #Building – Residential – Timber/Log
"xxx" => "GUP", #Pole-Guy 
"xxx" => "GUT", #Gutter/Flowline
"xxx" => "GUY", #Pole-Guy Wire
"xxx" => "H2O", #Water Line
"xxx" => "HHD", #Handhole - Traffic Signal - Double
"xxx" => "HHE", #Handhole – Electric
"xxx" => "HHF", #Handhole – Fiber Optic
"xxx" => "HHR", #Handhole – Traffic
"xxx" => "HHS", #Handhole – Traffic Fiber Optic
"xxx" => "HHT", #Handhole – Telephone
"xxx" => "HHV", #Handhole – TV
"xxx" => "HWL", #Headwall
"xxx" => "HYD", #Hydrant
"xxx" => "INL", #Inlet - Rectangular
"xxx" => "JUE", #QL-B Paint Mark Line - Electric
"xxx" => "JUF", #QL-B Paint Mark Line - Fiber Optic
"xxx" => "JUG", #QL-B Paint Mark Line - Gas
"xxx" => "JUM", #QL-B Paint Mark Line - Storm
"xxx" => "JUN", #QL-B Paint Mark Line - Sanitary
"xxx" => "JUP", #QL-B Paint Mark Line - Petroleum
"xxx" => "JUR", #QL-B Paint Mark Line - Traffic Signal
"xxx" => "JUS", #QL-B Paint Mark Line - Traffic Signal Fiber Optic
"xxx" => "JUT", #QL-B Paint Mark Line - Telephone
"xxx" => "JUV", #QL-B Paint Mark Line - Television
"xxx" => "JUW", #QL-B Paint Mark Line - Water
"xxx" => "LNB", #Lane Line – HMA
"xxx" => "LNC", #Lane Line – Concrete
"xxx" => "LND", #Landscape edge
"xxx" => "LNM", #Lane Paint Mark
"xxx" => "MBX", #Mailbox
"xxx" => "MCS", #Misc Concrete Slab
"xxx" => "MED", #Top Front of Median
"xxx" => "MHE", #Manhole – Electric
"xxx" => "MHF", #Manhole – Fiber
"xxx" => "MHG", #Gas Valve Vault
"xxx" => "MHM", #Manhole – Storm
"xxx" => "MHN", #Manhole -Sanitary
"xxx" => "MHT", #Manhole – Telephone
"xxx" => "MHW", #Water Valve Vault
"xxx" => "MSC", #Misc.
"xxx" => "MTE", #Meter – Electric
"xxx" => "MTG", #Meter – Gas
"xxx" => "MTW", #Meter – Water
"xxx" => "MWL", #Well - Inspection/Monitoring
"xxx" => "NPS", #No Pass
"xxx" => "PAB", #Patio Edge – HMA
"xxx" => "PAC", #Patio Edge – Concrete
"xxx" => "PAM", #Patio Edge – Masonry
"xxx" => "PAN", #Patio Edge – Stone
"xxx" => "PAR", #Patio Edge – Brick
"xxx" => "PDE", #Pedestal/Riser – Electric
"xxx" => "PDF", #Pedestal/Riser – Fiber
"xxx" => "PDT", #Pedestal/Riser – Telephone
"xxx" => "PDV", #Pedestal/Riser – TV
"xxx" => "PHB", #Phone Booth
"xxx" => "PLF", #Flag Pole
"xxx" => "PLT", #Pole-light only
"xxx" => "PMA", #Spot-Pavement – Aggregate
"xxx" => "PMB", #Spot-Pavement – HMA
"xxx" => "PMC", #Spot-Pavement – Concrete
"xxx" => "PMO", #Spot-Pavement – Oil & Chip
"xxx" => "PMR", #Spot-Pavement – Brick
"xxx" => "PPL", #Pole-Utility with light
"xxx" => "PPT", #Pole-Utility w/ transformer
"xxx" => "PPU", #Pole-Utility
"xxx" => "PRK", #Parking Meter
"xxx" => "PUG", #Pump – Gas
"xxx" => "PUM", #Pump – Storm
"xxx" => "PUN", #Pump – Sanitary
"xxx" => "PUP", #Pump – Petroleum
"xxx" => "PUW", #Pump – Water
"xxx" => "RCK", #Rock or Boulder
"xxx" => "RCL", #RR centerline
"xxx" => "RDR", #RR Derailer
"xxx" => "RGG", #Gas Regulator
"xxx" => "RIP", #Riprap
"xxx" => "RMP", #RR Mile Post Marker
"xxx" => "ROW", #ROW Monument
"xxx" => "RPA", #Ramp – Aggregate
"xxx" => "RPB", #Ramp – HMA
"xxx" => "RPC", #Ramp – Concrete
"xxx" => "RPF", #Ramp – Frame
"xxx" => "RPG", #Ramp – Ground
"xxx" => "RPM", #Ramp – Masonry
"xxx" => "RPN", #Ramp – Stone
"xxx" => "RPR", #Ramp – Brick
"xxx" => "RPS", #Ramp - Steel
"xxx" => "RPT", #Ramp – Wood
"xxx" => "RRC", #RR signal cabinet
"xxx" => "RRF", #RR Point of Frog - 1 point
"xxx" => "RRG", #RR crossing gate
"xxx" => "RRH", #RR Switch Heater 
"xxx" => "RRP", #RR Semaphore
"xxx" => "RRR", #RR top of rail
"xxx" => "RRS", #RR Point of Switch take shot on side of switch box
"xxx" => "RRT", #RR Tie
"xxx" => "RRW", #RR Switch Box
"xxx" => "RVT", #Revetment Mat
"xxx" => "RWC", #Retaining Wall – Concrete
"xxx" => "RWM", #Retaining Wall – Masonry
"xxx" => "RWN", #Retaining Wall – Stone
"xxx" => "RWR", #Retaining Wall – Brick
"xxx" => "RWS", #Retaining Wall – Steel
"xxx" => "RWT", #Retaining Wall – Timber
"xxx" => "SBE", #Splice Box – Electric
"xxx" => "SBF", #Splice Box – Fiber
"xxx" => "SBR", #Splice Box – Traffic
"xxx" => "SBS", #Splice Box – Traffic Fiber
"xxx" => "SBT", #Splice Box – Telephone
"xxx" => "SBV", #Splice Box – TV
"xxx" => "SHA", #Shoulder – Aggregate
"xxx" => "SHB", #Shoulder – HMA
"xxx" => "SHC", #Shoulder – Concrete
"xxx" => "SLB", #Slab – HMA
"xxx" => "SLC", #Slab – Concrete
"xxx" => "SNC", #Sign - Commercial
"xxx" => "SNE", #Sign - Warning - UG Electric
"xxx" => "SNF", #Sign - Warning - Fiber Optic
"xxx" => "SNG", #Sign - Warning - Gas
"xxx" => "SNL", #Sign - For Line Coding
"xxx" => "SNN", #Sign - Warning - Sanitary Line
"xxx" => "SNP", #Sign - Warning - Petroleum
"xxx" => "SNR", #Sign - Traffic
"xxx" => "SNS", #Sign - Traffic Fiber Optic
"xxx" => "SNT", #Sign - Warning - Telephone/Communications
"xxx" => "SNV", #Sign - Warning - Cable TV
"xxx" => "SNW", #Sign - Warning - Water line
"xxx" => "SPA", #Survey Point - Traverse Point
"xxx" => "SPB", #Survey Point - Axle
"xxx" => "SPC", #Survey Point - Cut Cross
"xxx" => "SPD", #Survey Point - Concrete Monument
"xxx" => "SPE", #Survey Point - Crimp Pipe
"xxx" => "SPF", #Survey Point - Benchmark
"xxx" => "SPG", #Survey Point - GPS Monument
"xxx" => "SPH", #Survey Point - Control Point
"xxx" => "SPI", #Survey Point - Iron Pipe
"xxx" => "SPJ", #Survey Point - Nail
"xxx" => "SPK", #Survey Point - Nail & Washer/Shiner
"xxx" => "SPL", #Survey Point - PK Nail
"xxx" => "SPM", #Survey Point - Mag Nail
"xxx" => "SPN", #Survey Point - ROW Marker
"xxx" => "SPO", #Survey Point - RR Spike
"xxx" => "SPP", #Survey Point - Pole Barn Spike
"xxx" => "SPQ", #Survey Point - Stone
"xxx" => "SPR", #Survey Point - Cotton Picker Spindle
"xxx" => "SPS", #Survey Point - Hub
"xxx" => "SPT", #Survey Point - Cut Square
"xxx" => "SPU", #Survey Point - Rebar
"xxx" => "SPV", #Survey Point - Drill Hole
"xxx" => "SPW", #Survey Point - Brass Marker
"xxx" => "SPX", #Survey Point - Iron Rod/Pin
"xxx" => "SPY", #Survey Point -
"xxx" => "SPZ", #Survey Point - Other
"xxx" => "STR", #Stairs / Porch
"xxx" => "SWA", #Sidewalk - Agg
"xxx" => "SWB", #Sidewalk - HMA/BIT
"xxx" => "SWC", #Sidewalk - Conc
"xxx" => "SWN", #Sidewalk - Stone/Rock
"xxx" => "SWR", #Sidewalk - Brick
"xxx" => "THW", #Thalweg - Lowest Point
"xxx" => "TIL", #Field Tile/ Downspout
"xxx" => "TNG", #Tank – Gas
"xxx" => "TNP", #Tank – Petroleum
"xxx" => "TNW", #Tank – Water
"xxx" => "TOE", #Toe of Slope
"xxx" => "TOP", #Top of Slope
"xxx" => "TRC", #Tree - Coniferous
"xxx" => "TRD", #Tree - Deciduous
"xxx" => "TRE", #Electric Transformer
"xxx" => "TRF", #Traffic Signal
"xxx" => "TRL", #Traffic Loop Detector
"xxx" => "TWR", #Transmission Tower
"xxx" => "UND", #Storm-underdrain
"xxx" => "VLG", #Valve – Gas
"xxx" => "VLN", #Valve – Sanitary
"xxx" => "VLP", #Valve – Petroleum
"xxx" => "VLW", #Valve – Water
"xxx" => "VNG", #Vent – Gas
"xxx" => "VNN", #Vent – Sanitary
"xxx" => "WAC", #Wall – not retaining –  Concrete
"xxx" => "WAF", #Wall – not retaining – Frame
"xxx" => "WAM", #Wall – not retaining – Masonry
"xxx" => "WAN", #Wall – not retaining – Stone
"xxx" => "WAR", #Wall – not retaining – Brick
"xxx" => "WAS", #Wall – not retaining –  Steel
"xxx" => "WAT", #Wall – not retaining – Timber 
"xxx" => "WDE", #Wooded Edge
"xxx" => "WEL", #Well - water
"xxx" => "WET", #Wetland
"xxx" => "WTR", #Water - Top Elevation
