package mainCodes;
use strict;
use warnings;

our %legalCodes = (
 "ACU" => "282 ACU", # Air Conditioning Unit
 "BAB" => "legal", # The outline of the face,sides,  top of the abutment.  A 3d line.
 "BAL" => "legal", # The outline of the face of the abutment and the face of the
                   # Wingwalls.  A 2d line, usually collected prismless.
 "BAR" => "legal", # Stop Bar - Painted
 "BAS" => "legal", # Bridge Approach Slab
 "BBA" => "legal", # Bridge Deck - AGG
 "BBB" => "legal", # Bridge Deck - BIT/HMA
 "BBC" => "legal", # Bridge Deck - Concrete
 "BBG" => "legal", # Buffalo Box - Gas
 "BBR" => "legal", # Bridge Deck - Bridk
 "BBS" => "legal", # The bridge seat elevation.  For elevation only.  Usually collected
                   # with the "hook".
 "BBV" => "legal", # Bridge Deck - Vinyl
 "BBW" => "legal", # Buffalo Box - Water
 "BCB" => "legal", # The top front of any curb or median on a bridge.
 "BDB" => "legal", # The line of the bit bridge deck.  A 3d line.
 "BDC" => "legal", # The line of the conc bridge deck.  A 3d line.
 "BDT" => "legal", # Bridge Deck Timber
 "BEX" => "legal", # The bridge expansion joint.  A 3d line.
 "BHR" => "legal", # Building# Bridge Handrail.  A 3D line.
 "BLC" => "legal", # The bottom of the concrete bridge beams.  Usually taken at
                   # the beginning middle and end oof each span of the bridge beams.
                   # Usually only required on the outside (upstream and downstream) beams.
 "BLS" => "legal", # The bottom of the steel bridge beams.  Usually taken at
                   # the beginning middle and end oof each span of the bridge beams.
                   # Usually only required on the outside (upstream and downstream) beams.
 "BLT" => "legal", # The bottom of the timber bridge beams.  Usually taken at
                   # the beginning middle and end oof each span of the bridge beams.
                   # Usually only required on the outside (upstream and downstream) beams.
 "BOL" => "legal", # Bollard
 "BOR" => "legal", # Boring/Coring
 "BPA" => "legal", # The bridge parapet. A 3d line.
 "BPC" => "legal", # The outline of the face of the pier cap. A 2d line usually
                   # collected "prismless".
 "BPR" => "legal", # The outline of the face, sides and top of the pier cap.  A 3d line.
 "BPT" => "legal", # The pier cap elevation,  For elevation only.  Usually collected
                   # with the "hook".
 "BRK" => "legal", # Break Line
 "BRR" => "legal", # Barrier Wall - base
 "BSC" => "legal", # Bridge Scupper
 "BSH" => "legal", # Bush / Shrub
 "BSL" => "legal", # Bush line / Hedgerow
 "BSS" => "legal", # Bridge Structural Steel
 "BWL" => "legal", # The outline of the face and sides of the bridge back wall.  A 3d line.
 "BWW" => "legal", # The outline of the face and sides of the wingwall.  A 3d line with
                   # points at each elevation change.
 "CBM" => "legal", # Catch Basin - Round Open
 "CKH" => "legal", # Control Point Check - Horizontal
 "CKV" => "legal", # Control Point Check - Vertical
 "CNA" => "legal", # Crown of roadway - Agg - use where there is no stripeing
 "CNB" => "legal", # Crown of roadway - HMA - use where there is no stripeing
 "CNC" => "legal", # Crown of roadway - CONC - use where there is no stripeing
 "CNP" => "legal", # Canopy
 "CNT" => "legal", # Traffic Signal Cantelever/Mast Arm
 "COL" => "legal", # Column
 "CPH" => "legal", # Control Point Horizontal
 "CPT" => "legal", # Cathodic Protection Test Station - Gas
 "CRB" => "legal", # Curb - Top Back - Concrete - this was changed back after a brief period of confusion
 "CRP" => "legal", # Crop Line
 "CRW" => "legal", # Crosswalk
 "CUB" => "legal", # Culvert - Box
 "CUE" => "legal", # Culvert - Elliptical
 "CUP" => "legal", # Culvert - Pipe
 "DAM" => "legal", # Levee/Dam Top
 "DCA" => "legal", # Driveway/Commercial Aggregate
 "DCB" => "legal", # Driveway/Commercial BIT/HMA
 "DCC" => "legal", # Driveway/Commercial Concrete
 "DCK" => "legal", # Deck
 "DCR" => "legal", # Driveway/Commercial Brick
 "DFA" => "legal", # Driveway/Field Aggregate
 "DFB" => "legal", # Driveway/Field BIT/HMA
 "DFC" => "legal", # Driveway/Field Concrete
 "DFG" => "legal", # Driveway/Field Ground
 "DFO" => "legal", # Driveway/Field Oil & Chip
 "DFR" => "legal", # Driveway/Field Brick
 "DPA" => "legal", # Driveway/Private-Residential Aggregate
 "DPB" => "legal", # Driveway/Private-Residential BIT/HMA
 "DPC" => "legal", # Driveway/Private-Residential Concrete
 "DPR" => "legal", # Driveway/Private-Residential Brick
 "DRA" => "legal", # Driveway/Entrance Aggregate
 "DRB" => "legal", # Driveway/Entrance HMA
 "DRC" => "legal", # Driveway/Entrance Concrete
 "DRR" => "legal", # Driveway/Entrance Brick
 "DSP" => "legal", # Downspout
 "DTH" => "legal", # Ditch Flowline
 "DTP" => "legal", # Paved Ditch Centerline
 "EOA" => "legal", # Edge of Pavement - Aggregate
 "EOB" => "legal", # Edge of Pavement - BIT/HMA
 "EOC" => "legal", # Edge of Pavement - Concrete
 "EOG" => "legal", # Edge of Dirt Roadway
 "EOO" => "legal", # Edge of Pavement - Oil & Chip
 "EOR" => "legal", # Edge of Pavement - Brick
 "FES" => "legal", # Flared End Section
 "FFL" => "legal", # Finish Floor Elevation
 "FNG" => "legal", # Fence Gate Post
 "FNI" => "legal", # Fence Line - Iron
 "FNL" => "legal", # Fence Line - Chain Link
 "FNM" => "legal", # Fence Line - Masonry
 "FNN" => "legal", # Fence Line - Stone/Rock
 "FNR" => "legal", # Fence Line - Brick
 "FNT" => "legal", # Fence Line - Wood
 "FNV" => "legal", # Fence Line - Vinyl
 "FNW" => "legal", # Fence Line - Wire
 "FNX" => "legal", # Fence Line - Barbed Wire
 "FOU" => "legal", # Foundation
 "GCC" => "legal", # Building Commercial Concrete
 "GCF" => "legal", # Building Commercial Wood Frame
 "GCM" => "legal", # Building Commercial Masonry
 "GCN" => "legal", # Building Commercial Stone/Rock
 "GCR" => "legal", # Building Commercial Brick
 "GCS" => "legal", # Building Commercial Steel
 "GCT" => "legal", # Building Commercial Timber/Log
 "GND" => "legal", # Ground Shot
 "GPC" => "legal", # Building Public Concrete
 "GPF" => "legal", # Building Public Wood Frame
 "GPM" => "legal", # Building Public Masonry
 "GPN" => "legal", # Building Public Stone/Rock
 "GPR" => "legal", # Building Public Brick
 "GPS" => "legal", # Building Public Steel
 "GPT" => "legal", # Building Public Timber/Log
 "GRC" => "legal", # Building Residential Concrete
 "GRF" => "legal", # Building Residential Wood Frame
 "GRL" => "legal", # Guard Rail
 "GRM" => "legal", # Building Residential Masonry
 "GRN" => "legal", # Building Residential Stone/Rock
 "GRR" => "legal", # Building Residential Brick
 "GRS" => "legal", # Building Residential Steel
 "GRT" => "legal", # Building Residential Timber/Log
 "GUP" => "legal", # Guy Pole
 "GUT" => "legal", # Gutter/Flowline
 "GUY" => "legal", # Guy Wire
 "H2O" => "legal", # Edge of Water
 "HHD" => "legal", # Handhole - Traffic Signal - Double
 "HHE" => "legal", # Handhole - Electric
 "HHF" => "legal", # Handhole - Fiber Optic
 "HHR" => "legal", # Handhole - Traffic
 "HHS" => "legal", # Handhole - Traffic Fiber Optic
 "HHT" => "legal", # Handhole - Telephone
 "HHV" => "legal", # Handhole - TV
 "HWL" => "legal", # Headwall
 "HYD" => "legal", # Hydrant
 "INL" => "legal", # Inlet - Rectangular
 "JUE" => "legal", # QL-B Paint Mark Line - Electric
 "JUF" => "legal", # QL-B Paint Mark Line - Fiber Optic
 "JUG" => "legal", # QL-B Paint Mark Line - Gas
 "JUM" => "legal", # QL-B Paint Mark Line - Storm
 "JUN" => "legal", # QL-B Paint Mark Line - Sanitary
 "JUP" => "legal", # QL-B Paint Mark Line - Petroleum
 "JUR" => "legal", # QL-B Paint Mark Line - Traffic Signal
 "JUS" => "legal", # QL-B Paint Mark Line - Traffic Signal Fiber Optic
 "JUT" => "legal", # QL-B Paint Mark Line - Telephone
 "JUV" => "legal", # QL-B Paint Mark Line - Television
 "JUW" => "legal", # QL-B Paint Mark Line - Water
 "LNB" => "legal", # Lane Line - BIT/HMA
 "LNC" => "legal", # Lane Line - Concrete
 "LND" => "legal", # Landscape Edge
 "LNM" => "legal", # Lane Paint Mark
 "MBX" => "legal", # Mailbox
 "MCS" => "legal", # Misc Concrete Slab
 "MED" => "legal", # Top Front of Median
 "MHE" => "legal", # Manhole Electrical
 "MHF" => "legal", # Manhole Fiber Optic
 "MHG" => "legal", # Manhole Gas
 "MHM" => "legal", # Mahhole Storm
 "MHN" => "legal", # Manhole Sanitary
 "MHT" => "legal", # Manhole Telephone/Communications
 "MHW" => "legal", # Manhole Water
 "MSC" => "legal", # Misc - added v6
 "MTE" => "legal", # Meter Electrical
 "MTG" => "legal", # Meter Gas
 "MTW" => "legal", # Meter Water
 "MWL" => "legal", # Monitoring/Inspection Well
 "NPS" => "legal", # No Pass Stripe
 "PAB" => "legal", # Patio Edge - Bit
 "PAC" => "legal", # Patio Edge - Conc
 "PAM" => "legal", # Patio Edge - Masonry
 "PAN" => "legal", # Patio Edge - Stone
 "PAR" => "legal", # Patio Edge - Brick
 "PDE" => "legal", # Pedestal Electric
 "PDF" => "legal", # Pedestal Fiber Optic
 "PDT" => "legal", # Pedestal Telephone/Communications
 "PDV" => "legal", # Pedestal Cable TV
 "PHB" => "legal", # Phone Booth
 "PLF" => "legal", # Flag Pole
 "PLT" => "legal", # Pole Light Only
 "PMA" => "legal", # Spot - Aggregate
 "PMB" => "legal", # Spot - HMA/BIT
 "PMC" => "legal", # Spot - Concrete
 "PMO" => "legal", # Spot - Oil & Chip
 "PMR" => "legal", # Spot - Brick
 "PPL" => "legal", # Pole Utility with Light
 "PPT" => "legal", # Pole Utility with Transformer
 "PPU" => "legal", # Pole Utility
 "PRK" => "legal", # Parking Meter
 "PUG" => "legal", # Pump - Gas
 "PUM" => "legal", # Pump - Storm
 "PUN" => "legal", # Pump - Sanitary
 "PUP" => "legal", # Pump - Petroleum
 "PUW" => "legal", # Pump - Water
 "RCK" => "legal", # Rock or Boulder
 "RCL" => "legal", # Railroad Centerline
 "RDR" => "legal", # RR Derailer
 "RGG" => "legal", # Regulator Gas
 "RIP" => "legal", # Rip Rap
 "RMP" => "legal", # RR Mile Post Marker
 "ROW" => "legal", # ROW Monument
 "RPA" => "legal", # Ramp - Aggregate
 "RPB" => "legal", # Ramp - Bit
 "RPC" => "legal", # Ramp - Conc
 "RPF" => "legal", # Ramp - Frame
 "RPG" => "legal", # Ramp - Earth
 "RPM" => "legal", # Ramp - Masonry
 "RPN" => "legal", # Ramp - Stone/Rock
 "RPR" => "legal", # Ramp - Brick
 "RPS" => "legal", # Ramp - Steel
 "RPT" => "legal", # Ramp - Wood
 "RRC" => "legal", # RR Signal Cabinet
 "RRF" => "legal", # RR Point of Frog - 1" point
 "RRG" => "legal", # RR Crossing Gate
 "RRH" => "legal", # RR Switch Heater
 "RRP" => "legal", # RR Semaphore
 "RRR" => "legal", # RR Rail - Top
 "RRS" => "legal", # RR Point of Switch take shot on side of switch box
 "RRT" => "legal", # RR Tie/Sleeper
 "RRW" => "legal", # RR Switch Box
 "RVT" => "legal", # Revetment Mat
 "RWC" => "legal", # Retaining Wall - Concrete
 "RWM" => "legal", # Retaining Wall - Masonry
 "RWN" => "legal", # Retaining Wall - Stone/Rock
 "RWR" => "legal", # Retaining Wall - Brick
 "RWS" => "legal", # Retaining Wall - Steel
 "RWT" => "legal", # Retaining Wall - Timber
 "SBE" => "legal", # Splice Box - Electrical
 "SBF" => "legal", # Splice Box - Fiber Optic
 "SBR" => "legal", # Splice Box - Traffic Signals
 "SBS" => "legal", # Splice Box - Traffic Fiber Optic
 "SBT" => "legal", # Splice Box - Telephone
 "SBV" => "legal", # Splice Box - Television
 "SHA" => "legal", # Shoulder - Aggregate
 "SHB" => "legal", # Shoulder - HMA/BIT
 "SHC" => "legal", # Shoulder - Concrete
 "SLB" => "legal", # Slab - Bit
 "SLC" => "legal", # Slab  - Conc
 "SNC" => "legal", # Sign - Commercial
 "SNE" => "legal", # Sign - Warning - UG Electric
 "SNF" => "legal", # Sign - Warning - Fiber Optic
 "SNG" => "legal", # Sign - Warning - Gas
 "SNL" => "legal", # Sign - For Line Coding
 "SNN" => "legal", # Sign - Warning - Sanitary Line
 "SNP" => "legal", # Sign - Warning - Petroleum
 "SNR" => "legal", # Sign - Traffic
 "SNS" => "legal", # Sign - Traffic Fiber Optic
 "SNT" => "legal", # Sign - Warning - Telephone/Communications
 "SNV" => "legal", # Sign - Warning - Cable TV
 "SNW" => "legal", # Sign - Warning - Water line
 "SPA" => "legal", # Survey Point - Traverse Point
 "SPB" => "legal", # Survey Point - Axle
 "SPC" => "legal", # Survey Point - Cut Cross
 "SPD" => "legal", # Survey Point - Concrete Monument
 "SPE" => "legal", # Survey Point - Crimp Pipe
 "SPF" => "legal", # Survey Point - Benchmark
 "SPG" => "legal", # Survey Point - GPS Monument
 "SPH" => "legal", # Survey Point - Control Point
 "SPI" => "legal", # Survey Point - Iron Pipe
 "SPJ" => "legal", # Survey Point - Nail
 "SPK" => "legal", # Survey Point - Nail & Washer/Shiner
 "SPL" => "legal", # Survey Point - PK Nail
 "SPM" => "legal", # Survey Point - Mag Nail
 "SPN" => "legal", # Survey Point - ROW Marker
 "SPO" => "legal", # Survey Point - RR Spike
 "SPP" => "legal", # Survey Point - Pole Barn Spike
 "SPQ" => "legal", # Survey Point - Stone
 "SPR" => "legal", # Survey Point - Cotton Picker Spindle
 "SPS" => "legal", # Survey Point - Hub
 "SPT" => "legal", # Survey Point - Cut Square
 "SPU" => "legal", # Survey Point - Rebar
 "SPV" => "legal", # Survey Point - Drill Hole
 "SPW" => "legal", # Survey Point - Brass Marker
 "SPX" => "legal", # Survey Point - Iron Rod/Pin
 "SPY" => "legal", # Survey Point -
 "SPZ" => "legal", # Survey Point - Other
 "STR" => "legal", # Stairs/Porch
 "SWA" => "legal", # Sidewalk - Agg
 "SWB" => "legal", # Sidewalk - HMA/BIT
 "SWC" => "legal", # Sidewalk - Conc
 "SWN" => "legal", # Sidewalk - Stone/Rock
 "SWR" => "legal", # Sidewalk - Brick
 "THW" => "legal", # Thalweg - Lowest Point
 "TIL" => "legal", # Tile
 "TNG" => "legal", # Tank - Gas 
 "TNP" => "legal", # Tank - Petroleum
 "TNW" => "legal", # Tank - Water
 "TOE" => "legal", # Toe of Slope
 "TOP" => "legal", # Top of Slope
 "TRC" => "legal", # Tree - Coniferous
 "TRD" => "legal", # Tree - Deciduous
 "TRE" => "legal", # Transformer
 "TRF" => "legal", # Traffic Signal
 "TRL" => "legal", # Traffic Loop Detector
 "TWR" => "legal", # Transmission Tower
 "UND" => "legal", # Underdrain
 "VLG" => "legal", # Valve - Gas
 "VLN" => "legal", # Valve - Sanitary
 "VLP" => "legal", # Valve - Petroleum
 "VLW" => "legal", # Valve - Water (By Hydrant)
 "VNG" => "legal", # Vent - Gas
 "VNN" => "legal", # Vent - Sanitary
 "WAC" => "legal", # Wall - Not Retaining -Concrete
 "WAF" => "legal", # Wall - Not Retaining -Frame
 "WAM" => "legal", # Wall - Not Retaining -Masonry
 "WAN" => "legal", # Wall - Not Retaining -Stone/Rock
 "WAR" => "legal", # Wall - Not Retaining -Brick
 "WAS" => "legal", # Wall - Not Retaining -Steel
 "WAT" => "legal", # Wall - Not Retaining -Timber
 "WDE" => "legal", # Wooded Edge
 "WEL" => "legal", # Well
 "WET" => "legal", # Wetland
 "WTR" => "legal", # Water - Top Elevation
###
 "103" => "legal",
 "111" => "legal",
 "112" => "legal",
 "118" => "legal",
 "119" => "legal",
 "134" => "legal",
 "135" => "legal",
 "200" => "legal",
 "207" => "legal",
 "210" => "legal", # parcel corner ILI
 "213" => "legal",
 "220" => "legal",
 "222" => "legal",
 "223" => "legal",
 "224" => "legal",
 "225" => "legal",
 "226" => "legal",
 "252" => "legal",
 "253" => "legal",
 "254" => "legal",
 "255" => "legal",
 "265" => "legal",
 "274" => "legal",
 "275" => "legal",
 "279" => "legal", # crosswalk
 "280" => "legal",
 "282" => "legal",
 "283" => "legal",
 "284" => "legal",
 "285" => "legal",
 "286" => "legal",
 "288" => "legal",
 "289" => "legal",
 "291" => "legal",
 "294" => "legal",
 "296" => "legal",
 "297" => "legal",
 "300" => "legal",
 "302" => "legal",
 "303" => "legal",
 "304" => "legal",
 "307" => "legal",
 "309" => "legal",
 "311" => "legal",
 "318" => "legal",
 "319" => "legal",
 "320" => "legal",
 "323" => "legal",
 "329" => "legal",
 "330" => "legal",
 "331" => "legal",
 "335" => "legal",
 "337" => "legal",
 "339" => "legal",
 "342" => "legal",
 "343" => "legal",
 "344" => "legal",
 "346" => "legal",
 "350" => "legal",
 "351" => "legal",
 "354" => "legal",
 "359" => "legal",
 "361" => "legal",
 "363" => "legal",
 "369" => "legal",
 "377" => "legal",
 "379" => "legal",
 "381" => "legal",
 "400" => "legal",
 "405" => "legal",
 "406" => "legal",
 "408" => "legal",
 "410" => "legal",
 "411" => "legal",
 "412" => "legal",
 "414" => "legal",
 "415" => "legal",
 "417" => "legal",
 "418" => "legal",
 "419" => "legal",
 "420" => "legal",
 "423" => "legal",
 "424" => "legal",
 "450" => "legal",
 "451" => "legal",
 "455" => "legal",
 "456" => "legal",
 "458" => "legal",
 "461" => "legal", # RR Mile Post
 "462" => "legal",
 "463" => "legal",
 "466" => "legal",
 "501" => "legal",
 "509" => "legal",
 "516" => "legal", # B6-24 added v6
 "575" => "legal",
 "578" => "legal",
 "579" => "legal", # Barrier Wall
 "600" => "legal",
 "601" => "legal",
 "602" => "legal",
 "604" => "legal",
 "605" => "legal",
 "606" => "legal",
 "607" => "legal",
 "609" => "legal",
 "611" => "legal",
 "612" => "legal",
 "613" => "legal",
 "615" => "legal",
 "616" => "legal",
 "618" => "legal",
 "619" => "legal",
 "620" => "legal",
 "621" => "legal",
 "623" => "legal",
 "624" => "legal",
 "626" => "legal",
 "627" => "legal",
 "628" => "legal",
 "629" => "legal",
 "631" => "legal",
 "633" => "legla",
 "634" => "legal",
 "635" => "legal",
 "640" => "legal",
 "641" => "legal",
 "649" => "legal",
 "650" => "legal",
 "652" => "legal",
 "654" => "legal",
 "656" => "legal",
 "664" => "legal",
 "666" => "legal",
 "668" => "legal",
 "669" => "legal",
 "673" => "legal",
 "674" => "legal",
 "678" => "legal", # Edge of Lanes - added v6
 "682" => "legal",
 "683" => "legal",
 "689" => "legal",
 "691" => "legal",
 "694" => "legal",
 "695" => "legal",
 "699" => "legal", # Misc - added 
 "776" => "legal", #
 "795" => "legal",
 "858" => "legal",
 "860" => "legal",
 "861" => "legal",
 "867" => "legal",
 "881" => "legal",
 "930" => "legal",
 "942" => "legal",
 "960" => "legal",
 "962" => "legal",
 "980" => "legal",
);

1;
