package typePrefixList;
use strict;
use warnings;

our %typePrefix = (
 "JUR" => "1", # 224 - TRAFFIC PAINT MARK QL-B
 "JUS" => "2", # 224 - TRAFFIC PAINT MARK FIBER OPTIC QL-B
 "TRL" => "3", # 224 - LOOP DETECTOR
 "BSW" => "1", # 291 - SIDEWALK BRIDGE
 "SWA" => "2", # 291 - SIDEWALK - AGG
 "SWB" => "3", # 291 - SIDEWALK - BIT/HMA
 "SWC" => "4", # 291 - SIDEWALK - CONC
 "SWR" => "5", # 291 - SIDEWALK - BRICK
 "WAC" => "1", # 294 - Wall - not retaining - Concrete
 "WAF" => "2", # 294 - Wall - not retaining - Frame
 "WAL" => "3", # 294 - Wall
 "WAN" => "4", # 294 - Wall - not retaining - Stone/Rock
 "WAM" => "5", # 294 - Wall - not retaining - Masonry
 "WAR" => "6", # 294 - Wall - not retaining - Brick
 "WAS" => "7", # 294 - Wall - not retaining - Steel
 "RWC" => "1", # 296 - Retaining Wall - Concrete
 "RWL" => "2", # 296 - Retaining Wall
 "RWN" => "3", # 296 - Retaining Wall - Stone
 "RWM" => "4", # 296 - Retaining Wall - Masonry
 "RWR" => "5", # 296 - Retaining Wall - Brick
 "RWS" => "6", # 296 - Retaining Wall - Steel
 "RWT" => "7", # 296 - Retaining Wall - Timber
 "PAA" => "1", # 297 - Patio Edge - Aggregate/Gravel
 "PAB" => "2", # 297 - Patio Edge - HMA
 "PAC" => "3", # 297 - Patio Edge - Concrete
 "PAN" => "4", # 297 - Patio Edge - Stone
 "PAR" => "5", # 297 - Patio Edge - Brick
 "SLA" => "6", # 297 - Slab - Aggregate/Gravel
 "SLB" => "7", # 297 - Slab - HMA/Bit
 "SLC" => "8", # 297 - Slab - Concrete
 "SLN" => "9", # 297 - Slab - Stone
 "SLR" => "10", # 297 - Slab - Brick
 "FNC" => "1", # 414 - Fence Line
 "FNI" => "2", # 414 - Fence Line - Iron
 "FNL" => "3", # 414 - Fence Line - Chain Link
 "FNT" => "4", # 414 - Fence Line - Wood
 "FNV" => "5", # 414 - Fence Line - Vinyl
 "FNW" => "6", # 414 - Fence Line - Wire
 "FNX" => "7", # 414 - Fence Line - Barbed Wire
 "SNC" => "1", # 423 - Sign - Commercial
 "TIL" => "1", # 304 - TILE
 "DSP" => "2", # 304 - DOWNSPOUT
 "GCC" => "1", # 600 - Building - Commercial - Concrete
 "GCF" => "2", # 600 - Building - Commercial - Wood Frame
 "GCM" => "3", # 600 - Building - Commercial - Masonry
 "GCR" => "4", # 600 - Building - Commercial - Brick
 "GCS" => "5", # 600 - Building - Commercial - Steel
 "GCT" => "6", # 600 - Building - Commercial - Timber/Log
 "GPC" => "1", # 601 - Building - Public - Concrete
 "GPF" => "2", # 601 - Building - Public - Wood Frame
 "GPM" => "3", # 601 - Building - Public - Masonry
 "GPR" => "4", # 601 - Building - Public - Brick
 "GPS" => "5", # 601 - Building - Public - Steel
 "GPT" => "6", # 601 - Building - Public - Timber/Log
 "GRC" => "1", # 602 - Building - Residential - Concrete
 "GRF" => "2", # 602 - Building - Residential - Wood Frame
 "GRM" => "3", # 602 - Building - Residential - Masonry
 "GRR" => "4", # 602 - Building - Residential - Brick
 "GRS" => "5", # 602 - Building - Residential - Steel
 "GRT" => "6", # 602 - Building - Residential - Timber/Log
 "BAB" => "1", # 615 - BRIDGE ABUTMENT TOP FACE
 "BPR" => "2", # 615 - BRIDGE PIER TOP FACE
 "BBA" => "1", # 619 - BRIDGE DECK SPOT AGG
 "BBB" => "5", # 619 - BRIDGE dECK SPOT BIT
 "BBC" => "6", # 619 - BRIDGE DECK SPOT CONC
 "BBR" => "4", # 619 - BRIDGE DECK SPOT BRICK
 "BDB" => "2", # 619 - BRIDGE DECK LINE BIT
 "BDC" => "3", # 619 - BRIDGE DECK LINE CONC
 "BDT" => "6", # 619 - Bridge Deck Timber
 "BWC" => "7", # 619 - Bridge Deck Sidewalk Conc
 "BPA" => "1", # 624 - BRIDGE PARAPET
 "BHR" => "2", # 624 - BRIDGE HANDRAIL
 "DCA" => "1", # 652 - Driveway/Commercial Aggregate
 "DCB" => "2", # 652 - Driveway/Commercial BIT/HMA
 "DCC" => "3", # 652 - Driveway/Commercial Concrete
 "DCG" => "4", # 652 - Driveway/Commercial Ground
 "DCR" => "5", # 652 - Driveway/Commercial Brick
 "DFA" => "1", # 654 - Driveway/Field Aggregate
 "DFB" => "2", # 654 - Driveway/Field BIT/HMA
 "DFC" => "3", # 654 - Driveway/Field Concrete
 "DFG" => "4", # 654 - Driveway/Field Ground
 "DFR" => "5", # 654 - Driveway/Field Brick
 "DPA" => "1", # 656 - Driveway/Private-Residential Aggregate
 "DPB" => "2", # 656 - Driveway/Private-Residential BIT/HMA
 "DPC" => "3", # 656 - Driveway/Private-Residential Concrete
 "DPG" => "4", # 656 - Driveway/Private-Residential Ground
 "DPR" => "5", # 656 - Driveway/Private-Residential Brick
 "DRA" => "1", # 649 - DRIVEWAY AGG
 "DRB" => "2", # 649 - DRIVEWAY BIT/HMA
 "DRC" => "3", # 649 - DRIVEWAY CONC
 "DRG" => "4", # 649 - FIELD ENTRANCE
 "DRR" => "5", # 649 - DRIVEWAY BRICK
 "RPB" => "1", # 659 - Ramp - HMA
 "RPC" => "2", # 659 - Ramp - Concrete
 "RPN" => "3", # 659 - Ramp - Stone
 "RPR" => "4", # 659 - Ramp - Brick
 "RPS" => "5", # 659 - Ramp - Steel
 "RPT" => "6", # 659 - Ramp - Wood
 "EOA" => "1", # 668 - EDGE OF PAVMENT AGG
 "EOB" => "2", # 668 - EDGE OF PAVMENT BIT/HMA
 "EOC" => "3", # 668 - EDGE OF PAVMENT CONC
 "EOR" => "4", # 668 - EDGE OF PAVMENT BRICK
 "LNB" => "2", # 678 - LANE LINES BIT/HMA
 "LNC" => "3", # 678 - LANE LINES CONC
 "SHA" => "1", # 674 - SHOULDER AGG
 "SHB" => "2", # 674 - SHOULDER BIT/HMA
 "SHC" => "3", # 674 - SHOULDER CONC
 "DSP" => "2", # 304 - DOWNSPOUT
);

1;
