package typePrefixList;
use strict;
use warnings;

our %typePrefix = (
 "JUR" => "1", # 224 - TRAFFIC PAINT MARK QL-B
 "JUS" => "2", # 224 - TRAFFIC PAINT MARK FIBER OPTIC QL-B
 "TRL" => "3", # 224 - LOOP DETECTOR
 "SWA" => "1", # 291 - SIDEWALK - AGG
 "SWB" => "2", # 291 - SIDEWALK - BIT/HMA
 "SWC" => "3", # 291 - SIDEWALK - CONC
 "SWN" => "4", # 291 - SIDEWALK - STONE
 "SWR" => "5", # 291 - SIDEWALK - BRICK
 "WAC" => "1", # 294 - Wall - not retaining - Concrete
 "WAF" => "2", # 294 - Wall - not retaining - Frame
 "WAM" => "3", # 294 - Wall - not retaining - Masonry
 "WAN" => "4", # 294 - Wall - not retaining - Stone/Rock
 "WAR" => "5", # 294 - Wall - not retaining - Brick
 "WAS" => "6", # 294 - Wall - not retaining - Steel
 "WAT" => "7", # 294 - Wall - not retaining - Timber
 "RWC" => "1", # 296 - Retaining Wall - Concrete
 "RWM" => "2", # 296 - Retaining Wall - Masonry
 "RWN" => "3", # 296 - Retaining Wall - Stone
 "RWR" => "4", # 296 - Retaining Wall - Brick
 "RWS" => "5", # 296 - Retaining Wall - Steel
 "RWT" => "6", # 296 - Retaining Wall - Timber
 "PAB" => "1", # 297 - Patio Edge - HMA
 "PAC" => "2", # 297 - Patio Edge - Concrete
 "PAM" => "3", # 297 - Patio Edge - Masonry
 "PAN" => "4", # 297 - Patio Edge - Stone
 "PAR" => "5", # 297 - Patio Edge - Brick
 "SLB" => "6", # 297 - Slab - HMA/Bit
 "SLC" => "7", # 297 - Slab - Concrete
 "FNI" => "1", # 414 - Fence Line - Iron
 "FNL" => "2", # 414 - Fence Line - Chain Link
 "FNM" => "3", # 414 - Fence Line - Masonry
 "FNN" => "4", # 414 - Fence Line - Stone
 "FNR" => "5", # 414 - Fence Line - Brick
 "FNT" => "6", # 414 - Fence Line - Wood
 "FNV" => "7", # 414 - Fence Line - Vinyl
 "FNW" => "8", # 414 - Fence Line - Wire
 "FNX" => "9", # 414 - Fence Line - Barbed Wire
 "TIL" => "1", # 304 - TILE
 "DSP" => "2", # 304 - DOWNSPOUT
 "GCC" => "1", # 600 - Building - Commercial - Concrete
 "GCF" => "2", # 600 - Building - Commercial - Wood Frame
 "GCM" => "3", # 600 - Building - Commercial - Masonry
 "GCN" => "4", # 600 - Building - Commercial - Stone
 "GCR" => "5", # 600 - Building - Commercial - Brick
 "GCS" => "6", # 600 - Building - Commercial - Steel
 "GCT" => "7", # 600 - Building - Commercial - Timber/Log
 "GPC" => "1", # 601 - Building - Public - Concrete
 "GPF" => "2", # 601 - Building - Public - Wood Frame
 "GPM" => "3", # 601 - Building - Public - Masonry
 "GPN" => "4", # 601 - Building - Public - Stone
 "GPR" => "5", # 601 - Building - Public - Brick
 "GPS" => "6", # 601 - Building - Public - Steel
 "GPT" => "7", # 601 - Building - Public - Timber/Log
 "GRC" => "1", # 602 - Building - Residential - Concrete
 "GRF" => "2", # 602 - Building - Residential - Wood Frame
 "GRM" => "3", # 602 - Building - Residential - Masonry
 "GRN" => "4", # 602 - Building - Residential - Stone
 "GRR" => "5", # 602 - Building - Residential - Brick
 "GRS" => "6", # 602 - Building - Residential - Steel
 "GRT" => "7", # 602 - Building - Residential - Timber/Log
 "CNA" => "1", # 607 - Crown of Road - Aggregate
 "CNB" => "2", # 607 - Crown of Road - HMA
 "CNC" => "3", # 607 - Crown of Road - Concrete
 "BAB" => "1", # 615 - BRIDGE ABUTMENT TOP FACE
 "BPR" => "2", # 615 - BRIDGE PIER TOP FACE
 "BBA" => "1", # 619 - BRIDGE DECK SPOT AGG
 "BBB" => "2", # 619 - BRIDGE DECK SPOT BIT
 "BBC" => "3", # 619 - BRIDGE DECK SPOT CONC
 "BBV" => "4", # 619 - BRIDGE DECK SPOT VINYL
 "BBR" => "5", # 619 - BRIDGE DECK SPOT BRICK
 "BDB" => "6", # 619 - BRIDGE DECK LINE BIT
 "BDC" => "7", # 619 - BRIDGE DECK LINE CONC
 "BDT" => "8", # 619 - Bridge Deck Timber
 "BPA" => "1", # 624 - BRIDGE PARAPET
 "BHR" => "2", # 624 - BRIDGE HANDRAIL
 "DCA" => "1", # 652 - Driveway/Commercial Aggregate
 "DCB" => "2", # 652 - Driveway/Commercial BIT/HMA
 "DCC" => "3", # 652 - Driveway/Commercial Concrete
 "DCR" => "4", # 652 - Driveway/Commercial Brick
 "DFA" => "1", # 654 - Driveway/Field Aggregate
 "DFB" => "2", # 654 - Driveway/Field BIT/HMA
 "DFC" => "3", # 654 - Driveway/Field Concrete
 "DFG" => "4", # 654 - Driveway/Field Ground
 "DFO" => "5", # 654 - Driveway/Field Oil & Chip
 "DFR" => "6", # 654 - Driveway/Field Brick
 "DPA" => "1", # 656 - Driveway/Private-Residential Aggregate
 "DPB" => "2", # 656 - Driveway/Private-Residential BIT/HMA
 "DPC" => "3", # 656 - Driveway/Private-Residential Concrete
 "DPR" => "4", # 656 - Driveway/Private-Residential Brick
 "DRA" => "1", # 649 - DRIVEWAY AGG
 "DRB" => "2", # 649 - DRIVEWAY BIT/HMA
 "DRC" => "3", # 649 - DRIVEWAY CONC
 "DRR" => "4", # 649 - DRIVEWAY BRICK
 "RPA" => "1", # 659 - Ramp - Aggregate
 "RPB" => "2", # 659 - Ramp - HMA
 "RPC" => "3", # 659 - Ramp - Concrete
 "RPF" => "4", # 659 - Ramp - Frame
 "RPG" => "5", # 659 - Ramp - Ground
 "RPM" => "6", # 659 - Ramp - Masonry
 "RPN" => "7", # 659 - Ramp - Stone
 "RPR" => "8", # 659 - Ramp - Brick
 "RPS" => "9", # 659 - Ramp - Steel
 "RPT" => "10", # 659 - Ramp - Wood
 "EOA" => "1", # 668 - EDGE OF PAVMENT AGG
 "EOB" => "2", # 668 - EDGE OF PAVMENT BIT/HMA
 "EOC" => "3", # 668 - EDGE OF PAVMENT CONC
 "EOG" => "4", # 668 - EDGE OF PAVMENT GROUND - Dirt Road
 "EOO" => "5", # 668 - EDGE OF PAVMENT OIL & CHIP
 "EOR" => "6", # 668 - EDGE OF PAVMENT BRICK
 "LNB" => "1", # 678 - LANE LINES BIT/HMA
 "LNC" => "2", # 678 - LANE LINES CONC
 "SHA" => "1", # 674 - SHOULDER AGG
 "SHB" => "2", # 674 - SHOULDER BIT/HMA
 "SHC" => "3", # 674 - SHOULDER CONC
);

1;
